# Generated by Django 3.0.5 on 2021-05-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzhut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='sizes',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='Invalid', max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='shapes',
            field=models.CharField(choices=[('regular', 'Regular'), ('square', 'Square')], default='Invalid', max_length=10),
        ),
    ]
