# Generated by Django 3.0.5 on 2021-05-02 21:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzhut', '0002_auto_20210503_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('onion', 'onion'), ('capsicum', 'capsicum'), ('tomato', 'tomato'), ('corn', 'corn')], default='Invalid', max_length=26),
        ),
    ]
