# Generated by Django 3.0.5 on 2021-05-03 07:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzhut', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapes', models.CharField(choices=[('regular', 'Regular'), ('square', 'Square')], default='Invalid', max_length=10)),
                ('sizes', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='Invalid', max_length=10)),
                ('toppings', multiselectfield.db.fields.MultiSelectField(choices=[('onion', 'onion'), ('capsicum', 'capsicum'), ('tomato', 'tomato'), ('corn', 'corn')], default='Invalid', max_length=26)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='shapes',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='size1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size4',
            field=models.CharField(default='', max_length=50),
        ),
    ]
