# Generated by Django 3.0.5 on 2021-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzhut', '0005_auto_20210503_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='pizzaname', max_length=50),
        ),
    ]
