# Generated by Django 3.0.5 on 2021-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzhut', '0006_pizza_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shapes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='shape',
            field=models.CharField(default='circle', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='mediumm', max_length=30),
        ),
        migrations.AddField(
            model_name='pizza',
            name='shape1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pizza',
            name='shape2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
