# Generated by Django 3.0.5 on 2021-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzhut', '0010_remove_pizza_shape1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='shape1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
