# Generated by Django 3.0.5 on 2021-05-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzhut', '0012_auto_20210503_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
