# Generated by Django 3.0.5 on 2021-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzhut', '0015_auto_20210503_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings2',
            field=models.CharField(max_length=15),
        ),
    ]
